# Generated by Django 4.1.3 on 2022-11-08 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesWorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_day', models.DateField()),
                ('task', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=150)),
                ('end_day_time', models.DateTimeField()),
                ('leave_reason', models.CharField(max_length=150)),
                ('leave_days', models.DateField()),
                ('deduction', models.FloatField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=70)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=70)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_img/')),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('department', models.CharField(max_length=70)),
                ('salary', models.FloatField()),
                ('paid_days', models.CharField(blank=True, max_length=70, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
