# Generated by Django 4.1.3 on 2022-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_remove_employeesworkdetails_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='leave_type',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], max_length=1),
        ),
    ]
