# Generated by Django 4.1.3 on 2022-11-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_employees_designation_employees_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('MGR', 'Manager'), ('SEE', 'Senior'), ('STE', 'Standard')], max_length=3, null=True),
        ),
    ]
