# Generated by Django 4.1.3 on 2022-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_project_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'Not Assigned'), ('A', 'Assigned'), ('C', 'Completed')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'Not Assigned'), ('A', 'Assigned'), ('C', 'Completed')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
