# Generated by Django 4.1.3 on 2022-11-15 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0011_remove_project_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesworkdetails',
            name='end_day_time',
        ),
        migrations.RemoveField(
            model_name='employeesworkdetails',
            name='working_day',
        ),
        migrations.AddField(
            model_name='employeesworkdetails',
            name='senior_employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeesworkdetails',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeesworkdetails',
            name='submit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeesworkdetails',
            name='project',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='hrm.project'),
        ),
        migrations.AlterField(
            model_name='employeesworkdetails',
            name='task',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='hrm.task'),
        ),
    ]
