# Generated by Django 4.1.3 on 2022-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_remove_employeesworkdetails_end_day_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesworkdetails',
            name='submit_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
