# Generated by Django 4.1.3 on 2022-11-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0015_task_employee_id_task_manager_task_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=250)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasktitle', to='hrm.project')),
            ],
        ),
    ]
