# Generated by Django 4.1.3 on 2022-11-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_tasktitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='hrm.tasktitle'),
        ),
    ]
