# Generated by Django 4.1.3 on 2022-11-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0017_alter_task_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='leave_type',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], max_length=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.tasktitle'),
        ),
    ]
