# Generated by Django 4.1.3 on 2022-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_tasktitle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Assigned'), ('C', 'Completed')], default='N', max_length=25, null=True),
        ),
    ]
