# Generated by Django 4.1.3 on 2022-11-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0021_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagement',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=25, null=True),
        ),
    ]
