# Generated by Django 4.1.3 on 2022-11-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0025_alter_leavemanagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='bank_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='pan_no',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='pf_no',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='pf_uan',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
