# Generated by Django 4.1.3 on 2022-11-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0026_employees_bank_account_no_employees_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='mobile',
            field=models.CharField(default='9999999999', max_length=10),
        ),
    ]
