# Generated by Django 4.1.3 on 2022-11-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0027_employees_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='mobile',
            field=models.CharField(default='9999999999', max_length=10),
        ),
    ]
