# Generated by Django 4.1.3 on 2022-11-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0028_alter_employees_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='mobile',
            field=models.CharField(default='1111111111', max_length=10),
        ),
    ]
