# Generated by Django 4.1.3 on 2022-11-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0031_employees_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
