# Generated by Django 4.1.3 on 2022-11-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0032_companycredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('final_amount', models.IntegerField()),
            ],
        ),
    ]
