# Generated by Django 4.1.3 on 2022-11-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0033_companyaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
