# Generated by Django 4.1.3 on 2022-11-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0034_alter_employees_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycredentials',
            name='final_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
