# Generated by Django 4.1.3 on 2022-12-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0035_companycredentials_final_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccount',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='companycredentials',
            name='final_amount',
        ),
    ]
