# Generated by Django 4.1.3 on 2022-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0036_remove_companyaccount_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='earning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
