# Generated by Django 4.1.3 on 2022-12-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0037_payslip_earning_payslip_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pincode',
            field=models.IntegerField(default=208023),
        ),
    ]
