# Generated by Django 4.1.3 on 2022-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0038_employees_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='branch',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
